# Variable and arguments LaTeX names
VN_OBSERVER_LATITUDE = "\\lambda_{\\text{obs}}"
VN_OBSERVER_LONGITUDE = "\\mu_{\\text{obs}}"
VN_OBSERVER_ALTITUDE = "A_{\\text{obs}}"
VN_PRESSURE = "P"
VN_TEMPERATURE = "T"

VN_JULIAN_DAY = "J_{\\text{d}}"
VN_JULIAN_EPHEMERIS_DAY = "J_{\\text{ed}}"
VN_JULIAN_CENTURY = "J_{\\text{c}}"
VN_JULIAN_EPHEMERIS_CENTURY = "J_{\\text{ec}}"
VN_JULIAN_EPHEMERIS_MILLENIUM = "J_{\\text{em}}"

VN_HELIOCENTRIC_LONGITUDE = "\\mu_{\\text{hel}}"
VN_HELIOCENTRIC_LATITUDE = "\\lambda_{\\text{hel}}"
VN_HELIOCENTRIC_RADIUS = "R_{\\text{hel}}"
VN_GEOCENTRIC_LONGITUDE = "\\mu_{\\text{geo}}"
VN_GEOCENTRIC_LATITUDE = "\\lambda_{\\text{geo}}"
VN_GEOCENTRIC_SUN_ASCENSION = "\\sigma_{\\text{geo}}"
VN_GEOCENTRIC_SUN_DECLINATION = "\\delta_{\\text{geo}}"

VN_MEAN_MOON_ELONGATION_FROM_SUN = "\\bar{e}_{\\bullet}"
VN_MEAN_SUN_ANOMALY = "\\bar{a}_{\\odot}"
VN_MEAN_MOON_ANOMALY = "\\bar{a}_{\\bullet}"
VN_MOON_LATITUDE_ARGUMENT = "\\lambda_{\\bullet}"
VN_ASCENDING_MOON_LONGITUDE = "\\mu_{\\bullet}"
VN_NUTATION_LONGITUDE = "\\mu_{\\text{nut}}"
VN_NUTATION_OBLIQUITY = "\\omega_{\\text{nut}}"

VN_MEAN_ELLIPTIC_OBLIQUITY = "\\bar{\\omega}_{\\text{ell}}"
VN_ELLIPTIC_OBLIQUITY = "\\omega_{\\text{ell}}"

VN_ABERRATION_CORRECTION = "\\beta"
VN_APPARENT_SUN_LONGITUDE = "\\tilde{\\mu}_{\\odot}"
VN_MEAN_SUN_LONGITUDE = "\\bar{\\mu}_{\\odot}"
VN_MEAN_SIDEREAL_GREENWICH_TIME = "\\bar{t}_{\\text{gw}}"
VN_APPARENT_SIDEREAL_GREENWICH_TIME = "\\tilde{t}_{\\text{gw}}"
VN_OBSERVER_LOCAL_HOUR = "h_{\\text{obs}}"

VN_SUN_EQUATORIAL_HORIZONTAL_PARALLAX = "\\xi_{\\text{hor}}"
VN_SUN_ASCENSION_PARALLAX = "\\xi_{\\text{asc}}"
VN_REDUCED_OBSERVER_LATITUDE = "\\lambda_{\\text{red}}"
VN_RADIAL_DISTANCE_FROM_EQUATORIAL_PLANE = "d_{\\text{eqt}}"
VN_RADIAL_DISTANCE_FROM_ROTATIONAL_AXIS = "d_{\\text{rot}}"
VN_TOPOCENTRIC_SUN_ASCENSION = "\\sigma_{\\text{top}}"
VN_TOPOCENTRIC_LOCAL_HOUR = "h_{\\text{top}}"
VN_TOPOCENTRIC_SUN_DECLINATION = "\\delta_{\\text{top}}"
VN_TOPOCENTRIC_APPARENT_ELEVATION = "\\tilde{\\eta}_{\\text{top}}"
VN_TOPOCENTRIC_ELEVATION_CORRECTION = "\\hat{\\eta}_{\\text{top}}"
VN_TOPOCENTRIC_ELEVATION = "\\eta_{\\text{top}}"
VN_TOPOCENTRIC_ASTRONOMICAL_AZIMUTH = "\\alpha_{\\star, \\text{top}}"
VN_TOPOCENTRIC_AZIMUTH = "\\alpha_{\\text{top}}"

VN_DAY_ANGLE = "H"
VN_SOLAR_CONSTANT = "\\Sigma"
VN_EXTRATERRESTRIAL_IRRADIANCE = "R_{\\text{ext}}"

VN_ABSOLUTE_AIRMASS = "m_{\\text{air}}"
VN_RELATIVE_AIRMASS = "m_{\\text{air, rel}}"
